import { HousingObservation, MortgageRate } from './measures';

export const SEED_MORTGAGE_RATES: MortgageRate[] = [
  {
    product: '30y_fixed',
    ratePct: 6.95,
    points: 0.2,
    weekEnding: '2026-09-17',
    source: 'Freddie Mac Primary Mortgage Market Survey (PMMS)',
    documentUrl: 'https://www.freddiemac.com/pmms'
  },
  {
    product: '15y_fixed',
    ratePct: 6.26,
    points: 0.2,
    weekEnding: '2026-09-17',
    source: 'Freddie Mac Primary Mortgage Market Survey (PMMS)',
    documentUrl: 'https://www.freddiemac.com/pmms'
  }
];

export const SEED_HOUSING_OBSERVATIONS: HousingObservation[] = [
  {
    id: 'cs-us-nsa-2026-06',
    sourceId: 'sp-case-shiller',
    seriesId: 'CSUSHPINSA',
    geographyId: 'US',
    geographyName: 'United States (National Composite)',
    measureKind: 'price_index',
    value: 336.663,
    unit: 'index_points',
    seasonalAdjustment: 'nsa',
    periodStart: '2026-04-01',
    periodEnd: '2026-06-30',
    releasedAt: '2026-08-27',
    lagMonths: 2,
    documentUrl: 'https://fred.stlouisfed.org/series/CSUSHPINSA',
    isSeed: true
  },
  {
    id: 'cs-us-sa-2026-06',
    sourceId: 'sp-case-shiller',
    seriesId: 'CSUSHPISA',
    geographyId: 'US',
    geographyName: 'United States (National Composite SA)',
    measureKind: 'price_index',
    value: 331.893,
    unit: 'index_points',
    seasonalAdjustment: 'sa',
    periodStart: '2026-04-01',
    periodEnd: '2026-06-30',
    releasedAt: '2026-08-27',
    lagMonths: 2,
    documentUrl: 'https://fred.stlouisfed.org/series/CSUSHPISA',
    isSeed: true
  },
  {
    id: 'cs-20city-yoy-2026-06',
    sourceId: 'sp-case-shiller',
    seriesId: 'SPCS20RNSA_YOY',
    geographyId: 'US-20CITY',
    geographyName: '20-City Composite YoY',
    measureKind: 'price_index',
    value: 2.1,
    unit: 'pct',
    seasonalAdjustment: 'nsa',
    periodStart: '2026-04-01',
    periodEnd: '2026-06-30',
    releasedAt: '2026-08-27',
    lagMonths: 2,
    documentUrl: 'https://www.spglobal.com/spdji/en/index-family/indicators/sp-cotality-case-shiller/',
    isSeed: true
  },
  {
    id: 'metro-nyc-median-price',
    sourceId: 'nar-zillow',
    seriesId: 'NYC_MEDIAN_SALE',
    geographyId: 'NYC',
    geographyName: 'New York Metro Area',
    measureKind: 'median_sale_price',
    value: 650000,
    unit: 'usd',
    seasonalAdjustment: 'nsa',
    periodStart: '2026-07-01',
    periodEnd: '2026-07-31',
    releasedAt: '2026-08-20',
    lagMonths: 1,
    documentUrl: 'https://www.zillow.com/research/data/',
    isSeed: true
  },
  {
    id: 'metro-lax-median-price',
    sourceId: 'nar-zillow',
    seriesId: 'LAX_MEDIAN_SALE',
    geographyId: 'LAX',
    geographyName: 'Los Angeles Metro Area',
    measureKind: 'median_sale_price',
    value: 885000,
    unit: 'usd',
    seasonalAdjustment: 'nsa',
    periodStart: '2026-07-01',
    periodEnd: '2026-07-31',
    releasedAt: '2026-08-20',
    lagMonths: 1,
    documentUrl: 'https://www.zillow.com/research/data/',
    isSeed: true
  },
  {
    id: 'metro-chi-median-price',
    sourceId: 'nar-zillow',
    seriesId: 'CHI_MEDIAN_SALE',
    geographyId: 'CHI',
    geographyName: 'Chicago Metro Area',
    measureKind: 'median_sale_price',
    value: 345000,
    unit: 'usd',
    seasonalAdjustment: 'nsa',
    periodStart: '2026-07-01',
    periodEnd: '2026-07-31',
    releasedAt: '2026-08-20',
    lagMonths: 1,
    documentUrl: 'https://www.zillow.com/research/data/',
    isSeed: true
  },
  {
    id: 'metro-dfw-median-price',
    sourceId: 'nar-zillow',
    seriesId: 'DFW_MEDIAN_SALE',
    geographyId: 'DFW',
    geographyName: 'Dallas-Fort Worth Metro Area',
    measureKind: 'median_sale_price',
    value: 410000,
    unit: 'usd',
    seasonalAdjustment: 'nsa',
    periodStart: '2026-07-01',
    periodEnd: '2026-07-31',
    releasedAt: '2026-08-20',
    lagMonths: 1,
    documentUrl: 'https://www.zillow.com/research/data/',
    isSeed: true
  },
  {
    id: 'metro-mia-median-price',
    sourceId: 'nar-zillow',
    seriesId: 'MIA_MEDIAN_SALE',
    geographyId: 'MIA',
    geographyName: 'Miami Metro Area',
    measureKind: 'median_sale_price',
    value: 495000,
    unit: 'usd',
    seasonalAdjustment: 'nsa',
    periodStart: '2026-07-01',
    periodEnd: '2026-07-31',
    releasedAt: '2026-08-20',
    lagMonths: 1,
    documentUrl: 'https://www.zillow.com/research/data/',
    isSeed: true
  }
];
